notifications:
  email: false

language: ruby
rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script: |
  awesome_bot README.md \
    --allow-dupe \
    --allow-ssl \
    --white-list https://github.com/opensourcecities/montreal/issues/new,https://github.com/opensourcecities/montreal.git

deploy:
  provider: script
  script: echo "deploy gh-pages"
  on:
    branch: master